import turtle

turtle.shape("turtle")
#T
turtle.penup()
turtle.left(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.penup()
turtle.right(180)
turtle.forward(50)
turtle.left(90)
turtle.pendown()
turtle.forward(100)

#M
turtle.penup()
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.pendown()
turtle.forward(100)
turtle.right(135)
turtle.forward(75)
turtle.left(90)
turtle.forward(75)
turtle.right(135)
turtle.forward(100)
